[package]
name = "hello_world_with_tests"
version = "0.1.0"
authors = [
    "David Wickes <dave.wickes@gmail.com>",
    "Tom Yandell <tom@yandell.me.uk>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
